name: Build

on:
  push:
    branches:
    - master
    - main
    tags:
    - 'v*'

jobs:
  build-natives:
    runs-on: windows-latest
    
    steps:
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    - name: test cmake
      run: cmake --version
      
    - uses: actions/checkout@v2
    - name: Prepare Build
      run: cmake -G "Visual Studio 16 2019" -S native -B native-build 
      
    - name: Build Natives
      run: cd native-build && cmake --build
      
    
    
  build-java:
    runs-on: windows-latest
    
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
        java-package: jdk
    - name: Test java
      run: java -version
    
    - uses: actions/checkout@v2
    - name: Maven build
      run: mvn package
      