name: Build

env:
  mainRevision: ${{ '0.0.1-SNAPHSOT' }}

on:
  push:
    branches:
    - master
    - main
    tags:
    - 'v*'

jobs:
  build-natives:
    runs-on: windows-latest
    
    steps:
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    - name: test cmake
      run: cmake --version
      
    - uses: actions/checkout@v2
    - name: Prepare Build
      run: cmake -G "Visual Studio 16 2019" -S native -B native-build 
      
    - name: Build Natives
      run: cd native-build && cmake --build
      
    
    
  build-java:
    runs-on: windows-latest
    
    steps:
    
    - name: Determine Release Revision
      run: echo "::set-output name=buildRevision::$(echo ${{github.ref}} | cut -dv -f2)"
      if: ${{ startsWith('refs/tags/v', github.ref) }}
    - name: Determine Nightly Revision
      run: echo "::set-output name=buildRevision::${{env.mainRevision}}"
      if: ${{ !startsWith('refs/tags/v', github.ref) }}
      
    - name: Output Build Revision
      run: echo ${{buildRevision}}
      
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
        java-package: jdk+fx
    - name: Test java
      run: java -version
    
    - uses: actions/checkout@v2
    - name: Maven build
      run: mvn -B -Drevision=${{buildRevision}} package
      